export function toEmoji(label) {
  return map[label] || '❓';
}

const map = {
  'kimono': '❓',
  'truck': '❓',
  'plunger': '❓',
  'desk': '❓',
  'school bus': '❓',
  'toaster': '❓',
  'shovel': '❓',
  'football helmet': '❓',
  'building': '❓',
  'fire engine': '❓',
  'cowboy boot': '❓',
  'sleeping bag': '❓',
  'airship': '❓',
  'spoon': '❓',
  'plane': '❓',
  'sliding door': '❓',
  'china cabinet': '❓',
  'vault': '❓',
  'bullet train': '❓',
  'microwave': '❓',
  'theater curtain': '❓',
  'barn': '❓',
  'oscilloscope': '❓',
  'pedestal': '❓',
  'lampshade': '❓',
  'gondola': '❓',
  'valley': '❓',
  'zucchini': '❓',
  'knot': '❓',
  'hot pot': '❓',
  'clock': '❓',
  'envelope': '❓',
  'tray': '❓',
  'bassinet': '❓',
  'cannon': '❓',
  'menu': '❓',
  'mouse': '❓',
  'stove': '❓',
  'barbell': '❓',
  'bath towel': '❓',
  'handkerchief': '❓',
  'pool table': '❓',
  'motor scooter': '❓',
  'goblet': '❓',
  'stone wall': '❓',
  'microphone': '❓',
  'washer': '❓',
  'hand': '❓',
  'gown': '❓',
  'tennis ball': '❓',
  'wig': '❓',
  'bathtub': '❓',
  'totem pole': '❓',
  'shower curtain': '❓',
  'broom': '❓',
  'measuring cup': '❓',
  'mountain tent': '❓',
  'table lamp': '❓',
  'barrow': '❓',
  'golf ball': '❓',
  'broccoli': '❓',
  'bed': '❓',
  'electric fan': '❓',
  'flute': '❓',
  'tobacco shop': '❓',
  'crock pot': '❓',
  'harmonica': '❓',
  'shoe shop': '❓',
  'water jug': '❓',
  'ping pong ball': '❓',
  'lipstick': '❓',
  'dining table': '❓',
  'banjo': '❓',
  'confectionery': '❓',
  'watch': '❓',
  'crossword puzzle': '❓',
  'modem': '❓',
  'saltshaker': '❓',
  'tile roof': '❓',
  'refrigerator': '❓',
  'mailbox': '❓',
  'pole': '❓',
  'cello': '❓',
  'flagpole': '❓',
  'water tower': '❓',
  'barber chair': '❓',
  'yawl': '❓',
  'soap dispenser': '❓',
  'stretcher': '❓',
  'steel drum': '❓',
  'bottlecap': '❓',
  'bathing cap': '❓',
  'comic book': '❓',
  'go kart': '❓',
  'dam': '❓',
  'parallel bars': '❓',
  'hand blower': '❓',
  'scoreboard': '❓',
  'space shuttle': '❓',
  'lakeside': '❓',
  'ocarina': '❓',
  'crutch': '❓',
  'cardigan': '❓',
  'milk can': '❓',
  'pencil box': '❓',
  'home theater': '❓',
  'feather boa': '❓',
  'solar dish': '❓',
  'dial telephone': '❓',
  'lighter': '❓',
  'light bulb': '❓',
  'sewing machine': '❓',
  'tv': '❓',
  'toilet tissue': '❓',
  'combination lock': '❓',
  'cloak': '❓',
  'bowl': '❓',
  'croquet ball': '❓',
  'container ship': '❓',
  'dogsled': '❓',
  'lock': '❓',
  'potters wheel': '❓',
  'plug': '❓',
  'horizontal bar': '❓',
  'castle': '❓',
  'rocking chair': '❓',
  'balloon': '❓',
  'ramen': '❓',
  'crayfish': '❓',
  'mixing bowl': '❓',
  'oboe': '❓',
  'nail': '❓',
  'hamburger': '❓',
  'patio': '❓',
  'spindle': '❓',
  'cucumber': '❓',
  'window shade': '❓',
  'street sign': '❓',
  'carousel': '❓',
  'rain barrel': '❓',
  'barrel': '❓',
  'carton': '❓',
  'baby bottle': '❓',
  'screw': '❓',
  'lion': '❓',
  'crate': '❓',
  'volleyball': '❓',
  'flower': '❓',
  'shirt': '❓',
  'koala': '❓',
  'necklace': '❓',
  'book': '❓',
  'sunglasses': '❓',
  'hair spray': '❓',
  'bicycle': '❓',
  'buckle': '❓',
  'shopping basket': '❓',
  'dog': '❓',
  'cellphone': '❓',
  'rubber eraser': '❓',
  'golfcart': '❓',
  'christmas stocking': '❓',
  'hourglass': '❓',
  'hammer': '❓',
  'pop bottle': '❓',
  'candle': '❓',
  'spotlight': '❓',
  'pickup': '❓',
  'pill bottle': '❓',
  'can opener': '❓',
  'freight car': '❓',
  'wardrobe': '❓',
  'maraca': '❓',
  'matchstick': '❓',
  'ant': '❓',
  'park bench': '❓',
  'teapot': '❓',
  'camera': '❓',
  'reel': '❓',
  'space heater': '❓',
  'bow': '❓',
  'racket': '❓',
  'perfume': '❓',
  'scale': '❓',
  'hotdog': '❓',
  'basketball': '❓',
  'sea urchin': '❓',
  'umbrella': '❓',
  'coral reef': '❓',
  'tripod': '❓',
  'strawberry': '❓',
  'sushi': '❓',
  'chime': '❓',
  'bus': '❓',
  'snowplow': '❓',
  'icecream': '❓',
  'soccer ball': '❓',
  'canoe': '❓',
  'velvet': '❓',
  'police van': '❓',
  'vending machine': '❓',
  'fireboat': '❓',
  'mailbag': '❓',
  'electric locomotive': '❓',
  'seashore': '❓',
  'glove': '❓',
  'cup': '❓',
  'plate rack': '❓',
  'car wheel': '❓',
  'cuirass': '❓',
  'projector': '❓',
  'mashed potato': '❓',
  'espresso maker': '❓',
  'pizza': '❓',
  'tricycle': '❓',
  'steam locomotive': '❓',
  'miniskirt': '❓',
  'hoopskirt': '❓',
  'baseball': '❓',
  'volcano': '❓',
  'dishwasher': '❓',
  'piggy bank': '❓',
  'orange': '❓',
  'garbage truck': '❓',
  'espresso': '❓',
  'corn': '❓',
  'iron': '❓',
  'honeycomb': '❓',
  'trombone': '❓',
  'apron': '❓',
  'ski mask': '❓',
  'tree': '❓',
  'joystick': '❓',
  'flashlight': '❓',
  'punching bag': '❓',
  'mask': '❓',
  'ladybug': '❓',
  'burrito': '❓',
  'chain': '❓',
  'dumbbell': '❓',
  'lotion': '❓',
  'wallet': '❓',
  'lens cap': '❓',
  'medicine chest': '❓',
  'planetarium': '❓',
  'artichoke': '❓',
  'snowmobile': '❓',
  'guacamole': '❓',
  'odometer': '❓',
  'screwdriver': '❓',
  'mortarboard': '❓',
  'cassette player': '❓',
  'paintbrush': '❓',
  'birdhouse': '❓',
  'car': '❓',
  'radio': '❓',
  'hat': '❓',
  'safety pin': '❓',
  'fountain': '❓',
  'tiger': '❓',
  'pinwheel': '❓',
  'restaurant': '❓',
  'bib': '❓',
  'display': '❓',
  'cabinet': '❓',
  'sundial': '❓',
  'tow truck': '❓',
  'stage': '❓',
  'whistle': '❓',
  'mobile home': '❓',
  'scorpion': '❓',
  'fish': '❓',
  'barometer': '❓',
  'bucket': '❓',
  'jigsaw puzzle': '❓',
  'key': '❓',
  'pick': '❓',
  'band aid': '❓',
  'power drill': '❓',
  'speedboat': '❓',
  'scissors': '❓',
  'lemon': '❓',
  'mushroom': '❓',
  'french horn': '❓',
  'bubble': '❓',
  'pineapple': '❓',
  'wool': '❓',
  'shopping cart': '❓',
  'gong': '❓',
  'tractor': '❓',
  'pajama': '❓',
  'scarf': '❓',
  'cd player': '❓',
  'marimba': '❓',
  'crib': '❓',
  'airliner': '❓',
  'cat': '❓',
  'ski': '❓',
  'laptop': '❓',
  'jack o lantern': '❓',
  'bread': '❓',
  'frying pan': '❓',
  'abacus': '❓',
  'butcher shop': '❓',
  'fries': '❓',
  'streetcar': '❓',
  'parking meter': '❓',
  'shower cap': '❓',
  'paper towel': '❓',
  'oil filter': '❓',
  'pot': '❓',
  'beer': '❓',
  'greenhouse': '❓',
  'strainer': '❓',
  'bee': '❓',
  'vase': '❓',
  'forklift': '❓',
  'guitar': '❓',
  'pomegranate': '❓',
  'backpack': '❓',
  'donut': '❓',
  'crane': '❓',
  'prayer rug': '❓',
  'dungeness crab': '❓',
  'corkscrew': '❓',
  'snorkel': '❓',
  'cauliflower': '❓',
  'sarong': '❓',
  'pencil sharpener': '❓',
  'sax': '❓',
  'ladle': '❓',
  'pants': '❓',
  'slot': '❓',
  'house': '❓',
  'parachute': '❓',
  'doormat': '❓',
  'window screen': '❓',
  'bird': '❓',
  'balance beam': '❓',
  'coil': '❓',
  'giant panda': '❓',
  'pillow': '❓',
  'disk brake': '❓',
  'pirate': '❓',
  'aircraft carrier': '❓',
  'knee pad': '❓',
  'car mirror': '❓',
  'trash can': '❓',
  'hair slide': '❓',
  'pen': '❓',
  'door': '❓',
  'safe': '❓',
  'cassette': '❓',
  'swing': '❓',
  'plate': '❓',
  'banana': '❓',
  'crash helmet': '❓',
  'drum': '❓',
  'face powder': '❓',
  'diaper': '❓',
  'poncho': '❓',
  'quilt': '❓',
  'pitcher': '❓',
  'toyshop': '❓',
  'coat': '❓',
  'binoculars': '❓',
  'acorn': '❓',
  'swimming trunks': '❓',
  'rotisserie': '❓',
  'abaya': '❓',
  'ballplayer': '❓',
  'folding chair': '❓',
  'water bottle': '❓',
  'taco': '❓',
  'starfish': '❓',
  'spider web': '❓',
  'cash machine': '❓',
  'hard disc': '❓',
  'manhole cover': '❓',
  'hamper': '❓',
  'letter opener': '❓',
  'oxygen mask': '❓',
  'cradle': '❓',
  'newspaper': '❓',
  'groom': '❓',
  'radiator': '❓',
  'plastic bag': '❓',
  'traffic light': '❓',
  'bell pepper': '❓',
  'cliff': '❓',
  'piano': '❓',
  'gas pump': '❓',
  'sock': '❓',
  'swab': '❓',
  'magnetic compass': '❓',
  'headphones': '❓',
  'worm fence': '❓',
  'organ': '❓',
  'cocktail shaker': '❓',
  'snail': '❓',
  'slug': '❓',
  'hook': '❓',
  'shoe': '❓',
  'mosque': '❓',
  'toilet': '❓',
  'vacuum': '❓',
  'harp': '❓',
  'scuba diver': '❓',
  'wine': '❓',
  'puck': '❓',
  'chiffonier': '❓',
  'accordion': '❓',
  'remote control': '❓',
  'printer': '❓',
  'violin': '❓',
  'magnifying glass': '❓',
  'sofa': '❓',
  'sunscreen': '❓',
  'sandbar': '❓',
  'steel arch bridge': '❓',
  'spatula': '❓',
  'keyboard': '❓',
  'switch': '❓',
  'rugby ball': '❓'
};
